packages:
  - "docs"
  - "packages/*"
  - "packages/create-skybridge/templates/demo"
  - "packages/create-skybridge/templates/blank"
  - "examples/*"

allowBuilds:
  esbuild: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
